better error message in CI format check

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -49,7 +49,8 @@ jobs:
         run: cargo clippy --all-targets -- -D warnings
 
       - name: finally, get picky about formatting
-        run: cargo fmt --check
+        run: |
+          cargo fmt +nightly --check || echo "::set-output name=error-message::Fix formatting errors by running \`just lint\` locally."
 
   cargo-deny:
     runs-on: ubuntu-latest
